import { CanvasElement, PaperColor } from '../types/canvas';

export const CANVAS_PALETTES = {
  fills: [
    { label: 'Transparent', value: 'transparent', preview: 'bg-transparent' },
    { label: 'White', value: '#FFFFFF', preview: 'bg-white' },
    { label: 'Workspace Gray', value: '#F3F4F6', preview: 'bg-gray-100' },
    { label: 'Yellow', value: '#FEF08A', preview: 'bg-yellow-200' },
    { label: 'Orange / Peach', value: '#FED7AA', preview: 'bg-orange-200' },
    { label: 'Rose / Red', value: '#FEE2E2', preview: 'bg-red-100' },
    { label: 'Sage / Green', value: '#DCFCE7', preview: 'bg-green-100' },
    { label: 'Teal / Cyan', value: '#CCFBF1', preview: 'bg-teal-100' },
    { label: 'Sky Blue', value: '#E0F2FE', preview: 'bg-sky-100' },
    { label: 'Indigo / Violet', value: '#EDE9FE', preview: 'bg-indigo-100' },
    { label: 'SyncSpace Teal', value: '#E6F0F2', preview: 'bg-cyan-100' },
    { label: 'Charcoal Dark', value: '#1F2937', preview: 'bg-gray-800' },
  ],
  strokes: [
    { label: 'Charcoal', value: '#1F2937', preview: 'bg-gray-800' },
    { label: 'Slate Gray', value: '#6B7280', preview: 'bg-gray-500' },
    { label: 'Light Gray', value: '#D1D5DB', preview: 'bg-gray-300' },
    { label: 'SyncSpace Teal', value: '#00667E', preview: 'bg-cyan-700' },
    { label: 'Sky Blue', value: '#0284C7', preview: 'bg-sky-600' },
    { label: 'Indigo', value: '#6366F1', preview: 'bg-indigo-500' },
    { label: 'Purple', value: '#8B5CF6', preview: 'bg-purple-500' },
    { label: 'Emerald Green', value: '#10B981', preview: 'bg-emerald-500' },
    { label: 'Amber Gold', value: '#D97706', preview: 'bg-amber-600' },
    { label: 'Warm Orange', value: '#F97316', preview: 'bg-orange-500' },
    { label: 'Coral Red', value: '#EF4444', preview: 'bg-red-500' },
    { label: 'Rose Pink', value: '#EC4899', preview: 'bg-pink-500' },
  ],
  stickyColors: [
    { key: 'sunflower', name: 'Sunflower Yellow', bg: '#FEF08A', border: '#CA8A04', text: '#713F12' },
    { key: 'coral', name: 'Warm Peach', bg: '#FED7AA', border: '#F97316', text: '#9A3412' },
    { key: 'sage', name: 'Mint Green', bg: '#D1FAE5', border: '#10B981', text: '#065F46' },
    { key: 'sky', name: 'Sky Blue', bg: '#BAE6FD', border: '#0EA5E9', text: '#0369A1' },
    { key: 'violet', name: 'Lavender', bg: '#EDE9FE', border: '#8B5CF6', text: '#5B21B6' },
    { key: 'rose', name: 'Soft Rose', bg: '#FFE4E6', border: '#FB7185', text: '#9F1239' },
    { key: 'kraft', name: 'Kraft Beige', bg: '#E7D6BC', border: '#B8A179', text: '#452B14' },
    { key: 'cream', name: 'Parchment White', bg: '#FFFDF8', border: '#D6C7B2', text: '#292524' },
  ] as const,
};

export const INITIAL_DEMO_CANVAS_ITEMS: CanvasElement[] = [
  {
    id: 'demo-frontend',
    type: 'rectangle',
    x: 140,
    y: 180,
    width: 200,
    height: 84,
    rotation: 0,
    color: 'sky',
    text: '🖥️ React Frontend\n(Client Web App)',
    fillColor: '#E0F2FE',
    strokeColor: '#0284C7',
    strokeWidth: 2,
    strokeStyle: 'solid',
    opacity: 1,
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    textColor: '#0369A1',
    zIndex: 1,
    createdAt: Date.now() - 50000,
    updatedAt: Date.now() - 50000,
  },
  {
    id: 'demo-gateway',
    type: 'rectangle',
    x: 440,
    y: 180,
    width: 200,
    height: 84,
    rotation: 0,
    color: 'violet',
    text: '⚡ API Gateway\n(Reverse Proxy & Auth)',
    fillColor: '#EDE9FE',
    strokeColor: '#7C3AED',
    strokeWidth: 2,
    strokeStyle: 'solid',
    opacity: 1,
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    textColor: '#5B21B6',
    zIndex: 2,
    createdAt: Date.now() - 40000,
    updatedAt: Date.now() - 40000,
  },
  {
    id: 'demo-auth',
    type: 'rectangle',
    x: 740,
    y: 100,
    width: 190,
    height: 74,
    rotation: 0,
    color: 'sunflower',
    text: '🔒 Auth Service\n(OAuth2 / Sessions)',
    fillColor: '#FEF08A',
    strokeColor: '#CA8A04',
    strokeWidth: 2,
    strokeStyle: 'solid',
    opacity: 1,
    fontSize: 13,
    fontWeight: 'bold',
    textAlign: 'center',
    textColor: '#854D0E',
    zIndex: 3,
    createdAt: Date.now() - 30000,
    updatedAt: Date.now() - 30000,
  },
  {
    id: 'demo-user',
    type: 'rectangle',
    x: 740,
    y: 250,
    width: 190,
    height: 74,
    rotation: 0,
    color: 'sage',
    text: '👥 User Service\n(Profile & Spaces)',
    fillColor: '#DCFCE7',
    strokeColor: '#16A34A',
    strokeWidth: 2,
    strokeStyle: 'solid',
    opacity: 1,
    fontSize: 13,
    fontWeight: 'bold',
    textAlign: 'center',
    textColor: '#15803D',
    zIndex: 4,
    createdAt: Date.now() - 25000,
    updatedAt: Date.now() - 25000,
  },
  {
    id: 'demo-db',
    type: 'diamond',
    x: 1030,
    y: 165,
    width: 170,
    height: 110,
    rotation: 0,
    color: 'coral',
    text: '💾 PostgreSQL\nDatabase',
    fillColor: '#FEE2E2',
    strokeColor: '#DC2626',
    strokeWidth: 2,
    strokeStyle: 'solid',
    opacity: 1,
    fontSize: 13,
    fontWeight: 'bold',
    textAlign: 'center',
    textColor: '#991B1B',
    zIndex: 5,
    createdAt: Date.now() - 20000,
    updatedAt: Date.now() - 20000,
  },
  // Connectors
  {
    id: 'conn-1',
    type: 'arrow',
    x: 340,
    y: 222,
    width: 100,
    height: 0,
    rotation: 0,
    color: 'sky',
    startPoint: { x: 340, y: 222 },
    endPoint: { x: 440, y: 222 },
    startBinding: { elementId: 'demo-frontend', side: 'right' },
    endBinding: { elementId: 'demo-gateway', side: 'left' },
    strokeColor: '#0284C7',
    strokeWidth: 2,
    strokeStyle: 'solid',
    endArrow: true,
    lineStyle: 'straight',
    text: 'HTTPS / WSS',
    fontSize: 11,
    textColor: '#475569',
    zIndex: 6,
    createdAt: Date.now() - 15000,
    updatedAt: Date.now() - 15000,
  },
  {
    id: 'conn-2',
    type: 'arrow',
    x: 640,
    y: 200,
    width: 100,
    height: -63,
    rotation: 0,
    color: 'violet',
    startPoint: { x: 640, y: 200 },
    endPoint: { x: 740, y: 137 },
    startBinding: { elementId: 'demo-gateway', side: 'right' },
    endBinding: { elementId: 'demo-auth', side: 'left' },
    strokeColor: '#7C3AED',
    strokeWidth: 2,
    strokeStyle: 'solid',
    endArrow: true,
    lineStyle: 'curved',
    zIndex: 7,
    createdAt: Date.now() - 14000,
    updatedAt: Date.now() - 14000,
  },
  {
    id: 'conn-3',
    type: 'arrow',
    x: 640,
    y: 240,
    width: 100,
    height: 47,
    rotation: 0,
    color: 'violet',
    startPoint: { x: 640, y: 240 },
    endPoint: { x: 740, y: 287 },
    startBinding: { elementId: 'demo-gateway', side: 'right' },
    endBinding: { elementId: 'demo-user', side: 'left' },
    strokeColor: '#7C3AED',
    strokeWidth: 2,
    strokeStyle: 'solid',
    endArrow: true,
    lineStyle: 'curved',
    zIndex: 8,
    createdAt: Date.now() - 13000,
    updatedAt: Date.now() - 13000,
  },
  {
    id: 'conn-4',
    type: 'arrow',
    x: 930,
    y: 137,
    width: 100,
    height: 83,
    rotation: 0,
    color: 'sunflower',
    startPoint: { x: 930, y: 137 },
    endPoint: { x: 1030, y: 220 },
    startBinding: { elementId: 'demo-auth', side: 'right' },
    endBinding: { elementId: 'demo-db', side: 'left' },
    strokeColor: '#D97706',
    strokeWidth: 2,
    strokeStyle: 'dashed',
    endArrow: true,
    lineStyle: 'curved',
    zIndex: 9,
    createdAt: Date.now() - 12000,
    updatedAt: Date.now() - 12000,
  },
  {
    id: 'conn-5',
    type: 'arrow',
    x: 930,
    y: 287,
    width: 100,
    height: -67,
    rotation: 0,
    color: 'sage',
    startPoint: { x: 930, y: 287 },
    endPoint: { x: 1030, y: 220 },
    startBinding: { elementId: 'demo-user', side: 'right' },
    endBinding: { elementId: 'demo-db', side: 'left' },
    strokeColor: '#16A34A',
    strokeWidth: 2,
    strokeStyle: 'dashed',
    endArrow: true,
    lineStyle: 'curved',
    zIndex: 10,
    createdAt: Date.now() - 11000,
    updatedAt: Date.now() - 11000,
  },
  // Sticky Notes
  {
    id: 'demo-sticky-1',
    type: 'sticky',
    x: 140,
    y: 380,
    width: 250,
    height: 190,
    rotation: 0,
    color: 'sunflower',
    title: '📌 Sprint Architecture',
    text: '• Drag shapes to move them\n• Connectors auto-update live\n• Double-click any shape to edit text\n• Shift+click or drag to multi-select',
    fontSize: 13,
    textColor: '#713F12',
    zIndex: 11,
    createdAt: Date.now() - 10000,
    updatedAt: Date.now() - 10000,
  },
  {
    id: 'demo-sticky-2',
    type: 'sticky',
    x: 440,
    y: 380,
    width: 250,
    height: 190,
    rotation: 0,
    color: 'sky',
    title: '⚡ Canvas Features',
    text: '• 13 fully functional tools\n• Undo / Redo (Ctrl+Z / Ctrl+Y)\n• Layers & Properties panel\n• Minimap & Infinite Pan / Zoom\n• Export PNG, SVG & JSON',
    fontSize: 13,
    textColor: '#0369A1',
    zIndex: 12,
    createdAt: Date.now() - 9000,
    updatedAt: Date.now() - 9000,
  },
];
